name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'


jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Apt
        run: |
          sudo apt update
          sudo apt install gnome-desktop-testing libasound2-dev libpulse-dev \
              libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
              libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
              libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
              libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev \
              libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev
      - name: Build examples
        run: |
          cargo build --examples --features "sdl3/build-from-source"

  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build examples
        run: |
          cargo build --examples --features "sdl3/build-from-source"

  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build examples
        run: |
          cargo build --examples --features "sdl3/build-from-source"

